// Generate last 5 years from current year
export const generateYears = (): string[] => {
  const currentYear = new Date().getFullYear();
  const years: string[] = [];
  for (let i = currentYear; i >= currentYear - 4; i--) {
    years.push(i.toString());
  }
  return years;
};

export const CHECKBOXES_YEARS = generateYears();

export const CHECKED_NAZWA_ZAMIERZENIA_BUD = [
  "budowa nowego/nowych obiektów budowlanych",
  "nadbudowa istniejącego/istniejących obiektów budowlanych",
  "rozbiórka istniejącego obiektu budowlanego",
  "rozbudowa istniejącego/istniejących obiektów budowlanych",
  "wykonanie robót budowlanych innych niż wymienione powyżej",
];

export const POSIBLE_CATEGORIES = [
  "I",
  "II",
  "III",
  "IV",
  "V",
  "VI",
  "VII",
  "VIII",
  "IX",
  "X",
  "XI",
  "XII",
  "XIII",
  "XIV",
  "XV",
  "XVI",
  "XVII",
  "XVIII",
  "XIX",
  "XX",
  "XXI",
  "XXII",
  "XXIII",
  "XXIV",
  "XXV",
  "XXVI",
  "XXVII",
  "XXVIII",
  "XXIX",
  "XXX",
];

export const POSIBLE_ORGANS: { [key: string]: string[] } = {
  dolnośląskie: [
    "Starosta Powiatu Bolesławiec",
    "Starosta Powiatu Dzierżoniów",
    "Starosta Powiatu Głogów",
    "Starosta Powiatu Góra",
    "Starosta Powiatu Jawor",
    "Starosta Powiatu Jelenia Góra",
    "Starosta Powiatu Kamienna Góra",
    "Starosta Powiatu Kłodzko",
    "Starosta Powiatu Legnica",
    "Starosta Powiatu Lubań",
    "Starosta Powiatu Lubin",
    "Starosta Powiatu Lwówek Śląski",
    "Starosta Powiatu Milicz",
    "Starosta Powiatu Oleśnica",
    "Starosta Powiatu Oława",
    "Starosta Powiatu Polkowice",
    "Starosta Powiatu Strzelin",
    "Starosta Powiatu Średzki",
    "Starosta Powiatu Świdnica",
    "Starosta Powiatu Trzebnica",
    "Starosta Powiatu Wałbrzych",
    "Starosta Powiatu Wołów",
    "Starosta Powiatu Wrocław",
    "Starosta Powiatu Ząbkowice Śląskie",
    "Starosta Powiatu Zgorzelec",
    "Starosta Powiatu Złotoryja",
    "Prezydent Miasta Jelenia Góra",
    "Prezydent Miasta Legnica",
    "Prezydent Miasta Wrocław",
    "Prezydent Miasta Wałbrzych",
  ],
  "kujawsko-pomorskie": [
    "Starosta Powiatu Aleksandrów Kujawski",
    "Starosta Powiatu Brodnica",
    "Starosta Powiatu Bydgoszcz",
    "Starosta Powiatu Chełmno",
    "Starosta Powiatu Golub-Dobrzyń",
    "Starosta Powiatu Grudziądz",
    "Starosta Powiatu Inowrocław",
    "Starosta Powiatu Lipno",
    "Starosta Powiatu Mogilno",
    "Starosta Powiatu Nakło nad Notecią",
    "Starosta Powiatu Radziejów",
    "Starosta Powiatu Rypin",
    "Starosta Powiatu Sępólno Krajeńskie",
    "Starosta Powiatu Świecie",
    "Starosta Powiatu Toruń",
    "Starosta Powiatu Tuchola",
    "Starosta Powiatu Wąbrzeźno",
    "Starosta Powiatu Włocławek",
    "Starosta Powiatu Żnin",
    "Prezydent Miasta Bydgoszcz",
    "Prezydent Miasta Grudziądz",
    "Prezydent Miasta Toruń",
    "Prezydent Miasta Włocławek",
  ],
  łódzkie: [
    "Starosta Powiatu Bełchatów",
    "Starosta Powiatu Brzeziny",
    "Starosta Powiatu Kutno",
    "Starosta Powiatu Łask",
    "Starosta Powiatu Łęczyca",
    "Starosta Powiatu Łowicz",
    "Starosta Powiatu Łódź Wschodni",
    "Starosta Powiatu Opoczno",
    "Starosta Powiatu Pabianice",
    "Starosta Powiatu Pajęczno",
    "Starosta Powiatu Piotrków Trybunalski",
    "Starosta Powiatu Poddębice",
    "Starosta Powiatu Radomsko",
    "Starosta Powiatu Rawa Mazowiecka",
    "Starosta Powiatu Sieradz",
    "Starosta Powiatu Skierniewice",
    "Starosta Powiatu Tomaszów Mazowiecki",
    "Starosta Powiatu Wieluń",
    "Starosta Powiatu Wieruszów",
    "Starosta Powiatu Zduńska Wola",
    "Starosta Powiatu Zgierz",
    "Prezydent Miasta Łódź",
    "Prezydent Miasta Piotrków Trybunalski",
    "Prezydent Miasta Skierniewice",
  ],
  lubelskie: [
    "Starosta Powiatu Biała Podlaska",
    "Starosta Powiatu Biłgoraj",
    "Starosta Powiatu Chełm",
    "Starosta Powiatu Hrubieszów",
    "Starosta Powiatu Janów Lubelski",
    "Starosta Powiatu Krasnystaw",
    "Starosta Powiatu Kraśnik",
    "Starosta Powiatu Lubartów",
    "Starosta Powiatu Lublin",
    "Starosta Powiatu Łęczna",
    "Starosta Powiatu Łuków",
    "Starosta Powiatu Opole Lubelskie",
    "Starosta Powiatu Parczew",
    "Starosta Powiatu Puławy",
    "Starosta Powiatu Radzyń Podlaski",
    "Starosta Powiatu Ryki",
    "Starosta Powiatu Świdnik",
    "Starosta Powiatu Tomaszów Lubelski",
    "Starosta Powiatu Włodawa",
    "Starosta Powiatu Zamość",
    "Prezydent Miasta Biała Podlaska",
    "Prezydent Miasta Chełm",
    "Prezydent Miasta Lublin",
    "Prezydent Miasta Zamość",
  ],
  lubuskie: [
    "Starosta Powiatu Gorzów Wielkopolski",
    "Starosta Powiatu Krosno Odrzańskie",
    "Starosta Powiatu Międzyrzecz",
    "Starosta Powiatu Nowa Sól",
    "Starosta Powiatu Słubice",
    "Starosta Powiatu Strzelce Krajeńskie",
    "Starosta Powiatu Sulęcin",
    "Starosta Powiatu Świebodzin",
    "Starosta Powiatu Wschowa",
    "Starosta Powiatu Zielona Góra",
    "Starosta Powiatu Żagań",
    "Starosta Powiatu Żary",
    "Prezydent Miasta Gorzów Wielkopolski",
    "Prezydent Miasta Zielona Góra",
  ],
  małopolskie: [
    "Starosta Powiatu Bocheński",
    "Starosta Powiatu Brzeski",
    "Starosta Powiatu Chrzanów",
    "Starosta Powiatu Dąbrowa Tarnowska",
    "Starosta Powiatu Gorlice",
    "Starosta Powiatu Kraków",
    "Starosta Powiatu Limanowa",
    "Starosta Powiatu Miechów",
    "Starosta Powiatu Myślenice",
    "Starosta Powiatu Nowy Sącz",
    "Starosta Powiatu Nowy Targ",
    "Starosta Powiatu Olkusz",
    "Starosta Powiatu Oświęcim",
    "Starosta Powiatu Proszowice",
    "Starosta Powiatu Sucha Beskidzka",
    "Starosta Powiatu Tarnów",
    "Starosta Powiatu Tatrzański",
    "Starosta Powiatu Wadowice",
    "Starosta Powiatu Wieliczka",
    "Prezydent Miasta Kraków",
    "Prezydent Miasta Nowy Sącz",
    "Prezydent Miasta Tarnów",
  ],
  mazowieckie: [
    "Starosta Powiatu Białobrzegi",
    "Starosta Powiatu Ciechanów",
    "Starosta Powiatu Garwolin",
    "Starosta Powiatu Gostyniński",
    "Starosta Powiatu Grodzisk Mazowiecki",
    "Starosta Powiatu Grójec",
    "Starosta Powiatu Kozienice",
    "Starosta Powiatu Legionowo",
    "Starosta Powiatu Lipsko",
    "Starosta Powiatu Łosice",
    "Starosta Powiatu Maków Mazowiecki",
    "Starosta Powiatu Miński",
    "Starosta Powiatu Mława",
    "Starosta Powiatu Nowy Dwór Mazowiecki",
    "Starosta Powiatu Ostrołęka",
    "Starosta Powiatu Ostrów Mazowiecka",
    "Starosta Powiatu Otwock",
    "Starosta Powiatu Piaseczno",
    "Starosta Powiatu Płock",
    "Starosta Powiatu Płońsk",
    "Starosta Powiatu Pruszków",
    "Starosta Powiatu Przasnysz",
    "Starosta Powiatu Przysucha",
    "Starosta Powiatu Pułtusk",
    "Starosta Powiatu Radom",
    "Starosta Powiatu Siedlce",
    "Starosta Powiatu Sierpc",
    "Starosta Powiatu Sokołów Podlaski",
    "Starosta Powiatu Szydłowiec",
    "Starosta Powiatu Warszawa Zachodnia",
    "Starosta Powiatu Węgrów",
    "Starosta Powiatu Wołomin",
    "Starosta Powiatu Wyszków",
    "Starosta Powiatu Zwoleń",
    "Starosta Powiatu Żuromin",
    "Starosta Powiatu Żyrardów",
    "Prezydent Miasta Ostrołęka",
    "Prezydent Miasta Płock",
    "Prezydent Miasta Radom",
    "Prezydent Miasta Siedlce",
    "Prezydent Miasta Warszawa",
  ],
  opolskie: [
    "Starosta Powiatu Brzeg",
    "Starosta Powiatu Głubczyce",
    "Starosta Powiatu Kędzierzyn-Koźle",
    "Starosta Powiatu Kluczbork",
    "Starosta Powiatu Krapkowice",
    "Starosta Powiatu Namysłów",
    "Starosta Powiatu Nysa",
    "Starosta Powiatu Oleski",
    "Starosta Powiatu Opole",
    "Starosta Powiatu Prudnik",
    "Starosta Powiatu Strzelce Opolskie",
    "Prezydent Miasta Opole",
  ],
  podkarpackie: [
    "Starosta Powiatu Bieszczadzki",
    "Starosta Powiatu Brzozów",
    "Starosta Powiatu Dębica",
    "Starosta Powiatu Jarosław",
    "Starosta Powiatu Jasło",
    "Starosta Powiatu Kolbuszowa",
    "Starosta Powiatu Krosno",
    "Starosta Powiatu Lesko",
    "Starosta Powiatu Leżajsk",
    "Starosta Powiatu Lubaczów",
    "Starosta Powiatu Łańcut",
    "Starosta Powiatu Mielec",
    "Starosta Powiatu Niżański",
    "Starosta Powiatu Przemyśl",
    "Starosta Powiatu Przeworsk",
    "Starosta Powiatu Ropczyce-Sędziszów",
    "Starosta Powiatu Rzeszów",
    "Starosta Powiatu Sanok",
    "Starosta Powiatu Stalowa Wola",
    "Starosta Powiatu Strzyżów",
    "Starosta Powiatu Tarnobrzeg",
    "Prezydent Miasta Krosno",
    "Prezydent Miasta Przemyśl",
    "Prezydent Miasta Rzeszów",
    "Prezydent Miasta Tarnobrzeg",
  ],
  podlaskie: [
    "Starosta Powiatu Augustów",
    "Starosta Powiatu Białystok",
    "Starosta Powiatu Bielsk Podlaski",
    "Starosta Powiatu Grajewo",
    "Starosta Powiatu Hajnówka",
    "Starosta Powiatu Kolno",
    "Starosta Powiatu Łomża",
    "Starosta Powiatu Mońki",
    "Starosta Powiatu Sejny",
    "Starosta Powiatu Siemiatycze",
    "Starosta Powiatu Sokółka",
    "Starosta Powiatu Suwałki",
    "Starosta Powiatu Wysokie Mazowieckie",
    "Starosta Powiatu Zambrów",
    "Prezydent Miasta Białystok",
    "Prezydent Miasta Łomża",
    "Prezydent Miasta Suwałki",
  ],
  pomorskie: [
    "Starosta Powiatu Bytów",
    "Starosta Powiatu Chojnice",
    "Starosta Powiatu Człuchów",
    "Starosta Powiatu Gdańsk",
    "Starosta Powiatu Gdynia",
    "Starosta Powiatu Kartuzy",
    "Starosta Powiatu Kościerzyna",
    "Starosta Powiatu Kwidzyn",
    "Starosta Powiatu Lębork",
    "Starosta Powiatu Malbork",
    "Starosta Powiatu Nowy Dwór Gdański",
    "Starosta Powiatu Pruszcz Gdański",
    "Starosta Powiatu Puck",
    "Starosta Powiatu Słupsk",
    "Starosta Powiatu Starogard Gdański",
    "Starosta Powiatu Sztum",
    "Starosta Powiatu Tczew",
    "Starosta Powiatu Wejherowo",
    "Prezydent Miasta Gdańsk",
    "Prezydent Miasta Gdynia",
    "Prezydent Miasta Słupsk",
    "Prezydent Miasta Sopot",
  ],
  śląskie: [
    "Starosta Powiatu Będzin",
    "Starosta Powiatu Bielsko-Biała",
    "Starosta Powiatu Bieruń-Lędziny",
    "Starosta Powiatu Bytom",
    "Starosta Powiatu Chorzów",
    "Starosta Powiatu Cieszyn",
    "Starosta Powiatu Częstochowa",
    "Starosta Powiatu Dąbrowa Górnicza",
    "Starosta Powiatu Gliwice",
    "Starosta Powiatu Jastrzębie-Zdrój",
    "Starosta Powiatu Jaworzno",
    "Starosta Powiatu Katowice",
    "Starosta Powiatu Kłobuck",
    "Starosta Powiatu Lubliniec",
    "Starosta Powiatu Mikołów",
    "Starosta Powiatu Mysłowice",
    "Starosta Powiatu Myszków",
    "Starosta Powiatu Piekary Śląskie",
    "Starosta Powiatu Pszczyna",
    "Starosta Powiatu Racibórz",
    "Starosta Powiatu Ruda Śląska",
    "Starosta Powiatu Rybnik",
    "Starosta Powiatu Siemianowice Śląskie",
    "Starosta Powiatu Sosnowiec",
    "Starosta Powiatu Świętochłowice",
    "Starosta Powiatu Tarnowskie Góry",
    "Starosta Powiatu Tychy",
    "Starosta Powiatu Wodzisław Śląski",
    "Starosta Powiatu Zabrze",
    "Starosta Powiatu Zawiercie",
    "Starosta Powiatu Żory",
    "Starosta Powiatu Żywiec",
    "Prezydent Miasta Bielsko-Biała",
    "Prezydent Miasta Bytom",
    "Prezydent Miasta Chorzów",
    "Prezydent Miasta Częstochowa",
    "Prezydent Miasta Dąbrowa Górnicza",
    "Prezydent Miasta Gliwice",
    "Prezydent Miasta Jastrzębie-Zdrój",
    "Prezydent Miasta Jaworzno",
    "Prezydent Miasta Katowice",
    "Prezydent Miasta Mysłowice",
    "Prezydent Miasta Piekary Śląskie",
    "Prezydent Miasta Ruda Śląska",
    "Prezydent Miasta Rybnik",
    "Prezydent Miasta Siemianowice Śląskie",
    "Prezydent Miasta Sosnowiec",
    "Prezydent Miasta Świętochłowice",
    "Prezydent Miasta Tychy",
    "Prezydent Miasta Zabrze",
    "Prezydent Miasta Żory",
  ],
  świętokrzyskie: [
    "Starosta Powiatu Busko-Zdrój",
    "Starosta Powiatu Jędrzejów",
    "Starosta Powiatu Kazimierza Wielka",
    "Starosta Powiatu Kielce",
    "Starosta Powiatu Końskie",
    "Starosta Powiatu Opatów",
    "Starosta Powiatu Ostrowiecki",
    "Starosta Powiatu Pińczów",
    "Starosta Powiatu Sandomierz",
    "Starosta Powiatu Skarżysko-Kamienna",
    "Starosta Powiatu Starachowice",
    "Starosta Powiatu Staszów",
    "Starosta Powiatu Włoszczowa",
    "Prezydent Miasta Kielce",
  ],
  "warmińsko-mazurskie": [
    "Starosta Powiatu Bartoszyce",
    "Starosta Powiatu Braniewo",
    "Starosta Powiatu Działdowo",
    "Starosta Powiatu Elbląg",
    "Starosta Powiatu Ełk",
    "Starosta Powiatu Giżycko",
    "Starosta Powiatu Gołdap",
    "Starosta Powiatu Iława",
    "Starosta Powiatu Kętrzyn",
    "Starosta Powiatu Lidzbark Warmiński",
    "Starosta Powiatu Mrągowo",
    "Starosta Powiatu Nidzica",
    "Starosta Powiatu Nowe Miasto Lubawskie",
    "Starosta Powiatu Olecko",
    "Starosta Powiatu Olsztyn",
    "Starosta Powiatu Ostróda",
    "Starosta Powiatu Pisz",
    "Starosta Powiatu Szczytno",
    "Starosta Powiatu Węgorzewo",
    "Prezydent Miasta Elbląg",
    "Prezydent Miasta Olsztyn",
  ],
  wielkopolskie: [
    "Starosta Powiatu Chodzieski",
    "Starosta Powiatu Czarnków-Trzcianka",
    "Starosta Powiatu Gniezno",
    "Starosta Powiatu Gostyń",
    "Starosta Powiatu Grodzisk Wielkopolski",
    "Starosta Powiatu Jarocin",
    "Starosta Powiatu Kalisz",
    "Starosta Powiatu Kępno",
    "Starosta Powiatu Kolski",
    "Starosta Powiatu Konin",
    "Starosta Powiatu Kościan",
    "Starosta Powiatu Krotoszyn",
    "Starosta Powiatu Leszno",
    "Starosta Powiatu Międzychód",
    "Starosta Powiatu Nowy Tomyśl",
    "Starosta Powiatu Oborniki",
    "Starosta Powiatu Ostrów Wielkopolski",
    "Starosta Powiatu Ostrzeszów",
    "Starosta Powiatu Piła",
    "Starosta Powiatu Pleszew",
    "Starosta Powiatu Poznań",
    "Starosta Powiatu Rawicz",
    "Starosta Powiatu Słupca",
    "Starosta Powiatu Szamotuły",
    "Starosta Powiatu Średzki",
    "Starosta Powiatu Śrem",
    "Starosta Powiatu Turek",
    "Starosta Powiatu Wągrowiec",
    "Starosta Powiatu Wolsztyński",
    "Starosta Powiatu Wrzesiński",
    "Starosta Powiatu Złotów",
    "Prezydent Miasta Kalisz",
    "Prezydent Miasta Konin",
    "Prezydent Miasta Leszno",
    "Prezydent Miasta Poznań",
  ],
  zachodniopomorskie: [
    "Starosta Powiatu Białogard",
    "Starosta Powiatu Choszczno",
    "Starosta Powiatu Drawsko Pomorskie",
    "Starosta Powiatu Goleniów",
    "Starosta Powiatu Gryfice",
    "Starosta Powiatu Gryfino",
    "Starosta Powiatu Kamień Pomorski",
    "Starosta Powiatu Kołobrzeg",
    "Starosta Powiatu Koszalin",
    "Starosta Powiatu Łobez",
    "Starosta Powiatu Myślibórz",
    "Starosta Powiatu Pyrzyce",
    "Starosta Powiatu Sławno",
    "Starosta Powiatu Stargard",
    "Starosta Powiatu Szczecin",
    "Starosta Powiatu Szczecinek",
    "Starosta Powiatu Świdwin",
    "Starosta Powiatu Wałcz",
    "Prezydent Miasta Koszalin",
    "Prezydent Miasta Szczecin",
    "Prezydent Miasta Świnoujście",
  ],
};

export const DEFAULT_COLUMNS = [
  "nazwa_organu",
  "data_wplywu_wniosku",
  "numer_decyzji",
  "numer_decyzji_urzedu",
  "data_wydania_decyzji",
  "nazwa_inwestor",
  "wojewodztwo",
  "miasto",
  "nazwa_zam_budowlanego",
  "kubatura",
  "projektant_nazwisko",
  "projektant_imie",
];
